# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 

target 'ios-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ios-sample
  pod 'AppsFlyerFramework', '6.2.5'
  #pod 'AppsFlyerFramework', '6.3.2'
  pod 'wrappedaf', :path => 'wrappedaf'
end
