# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unifieddeeplink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unifieddeeplink
  pod 'AppsFlyerFramework', '6.2.4'
  #pod 'AppsFlyerFramework/Strict','6.1.1'

end
